//! Headful live simulation of transfer rates across every corpus.
//!
//! A localhost web tool: pick a cap and an iteration count, press Run, and watch
//! encode/decode throughput fill in per file per level, beside the pinned C
//! v1.5.7 arm.
//!
//! PROTOCOL. Same shape as `m7board.rs`, which is what makes the numbers mean
//! anything: phases timed separately (as C's `-b` does), best-of-N with a
//! discarded warmup, decode into a REUSED buffer via `decompress_into`, and
//! checksum OFF on our arm to match `ZSTD_c_checksumFlag = 0` in `zstd -b`.
//! That changes the MEASUREMENT, not the product -- the shipped default is
//! still `checksum: true`.
//!
//! Every encode figure ships with a SAME-ARM SPREAD: two independent best-of-N
//! arms over identical input, reported as +-%. This is a live desktop, so that
//! number is the reader's guard against over-reading a small gap. Compressed
//! SIZES are deterministic and carry no such caveat.
//!
//! Requests are served one at a time on purpose -- concurrent measurement would
//! have the arms contending for the same cores.
//!
//! Usage: `cargo run --release -p rusty_zstd-bench --example simserver [port]`
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;
use std::time::Instant;

const PAGE: &str = include_str!("simserver.html");
const ZSTD: &str = "third_party/zstd/extracted/zstd-v1.5.7-win64/zstd.exe";

/// name, path, bytes, category, provenance
type Entry = (String, PathBuf, u64, String, &'static str);

/// The browser addresses files by NAME, never by path, and this is the only
/// table that maps one to the other -- so a scan decides what is reachable,
/// not the request. Replaced wholesale by `/api/corpora?dir=`.
static REGISTRY: Mutex<Vec<Entry>> = Mutex::new(Vec::new());

/// PROVENANCE IS PART OF THE RESULT. Half of `corpora/data` is synthetic by
/// recipe (see `corpora/README.md`) and half is the real Silesia corpus; a
/// rate measured on `zeros-32m` and a rate measured on `dickens` are not the
/// same kind of fact, and the board should say which is which.
fn builtin_meta(name: &str) -> (&'static str, &'static str) {
    match name {
        // Silesia -- real files, original 2002/2003 content.
        "dickens" | "webster" | "reymont" => ("natural text", "real"),
        "xml" | "nci" => ("structured text", "real"),
        "mozilla" | "ooffice" | "samba" => ("binary / executable", "real"),
        "sao" | "x-ray" | "osdb" | "mr" => ("scientific / numeric", "real"),
        // Generated by recipe -- deliberately degenerate edge cases.
        "zeros-32m" | "zeros-1m" => ("degenerate: all-zero", "synthetic"),
        "incomp-32m" => ("degenerate: incompressible", "synthetic"),
        "versions-16m" => ("degenerate: repetitive", "synthetic"),
        "text-32m" => ("degenerate: repeating pangram", "synthetic"),
        "jsonlog-16m" | "smallmsg-8m" => ("structured text", "synthetic"),
        _ => ("other", "real"),
    }
}

/// Real files off the user's disk get their type from the extension.
fn ext_category(p: &Path) -> &'static str {
    let e = p
        .extension()
        .map(|s| s.to_string_lossy().to_ascii_lowercase())
        .unwrap_or_default();
    match e.as_str() {
        "txt" | "md" | "log" | "csv" | "tsv" | "rst" | "tex" => "natural text",
        "rs" | "c" | "h" | "cpp" | "hpp" | "py" | "js" | "ts" | "go" | "java" | "sh" | "ps1" => {
            "source code"
        }
        "json" | "xml" | "html" | "htm" | "yaml" | "yml" | "toml" | "svg" => "structured text",
        "exe" | "dll" | "so" | "dylib" | "o" | "a" | "lib" | "pdb" | "bin" | "wasm" => {
            "binary / executable"
        }
        "jpg" | "jpeg" | "png" | "gif" | "webp" | "mp3" | "mp4" | "mkv" | "zip" | "gz" | "zst"
        | "xz" | "7z" | "bz2" | "pdf" | "docx" | "xlsx" | "pptx" => "already compressed",
        "wav" | "bmp" | "tif" | "tiff" | "raw" | "fits" => "uncompressed media",
        _ => "other",
    }
}

fn builtin() -> Vec<Entry> {
    let mut v = Vec::new();
    for dir in ["corpora/data/generated", "corpora/data/silesia"] {
        let Ok(rd) = std::fs::read_dir(dir) else { continue };
        for e in rd.flatten() {
            let p = e.path();
            if !p.is_file() {
                continue;
            }
            let Ok(md) = e.metadata() else { continue };
            if md.len() < 4096 {
                continue;
            }
            let name = p.file_name().unwrap().to_string_lossy().to_string();
            if name.ends_with(".zst") || name.starts_with('.') {
                continue;
            }
            let (cat, prov) = builtin_meta(&name);
            v.push((name, p, md.len(), cat.to_string(), prov));
        }
    }
    v.sort_by(|a, b| a.0.cmp(&b.0));
    v
}

const SKIP_DIRS: &[&str] = &[".git", "target", "node_modules", ".cargo", "corpora"];

/// Walk a real directory for real files. Bounded: skips build/VCS trees, takes
/// only files big enough to time meaningfully, and stops at a sane count so a
/// stray `C:\` never turns into a million-row board.
fn scan_dir(root: &Path, out: &mut Vec<Entry>, depth: u32, min: u64, cap_files: usize) {
    if depth > 5 || out.len() >= cap_files {
        return;
    }
    let Ok(rd) = std::fs::read_dir(root) else { return };
    let mut dirs = Vec::new();
    for e in rd.flatten() {
        if out.len() >= cap_files {
            return;
        }
        let p = e.path();
        let Ok(md) = e.metadata() else { continue };
        let name = p.file_name().unwrap_or_default().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if md.is_dir() {
            if !SKIP_DIRS.contains(&name.as_str()) {
                dirs.push(p);
            }
        } else if md.is_file() && md.len() >= min {
            // Disambiguate identical basenames from different folders.
            let label = if out.iter().any(|(n, _, _, _, _)| *n == name) {
                format!("{}  ({})", name, root.file_name().unwrap_or_default().to_string_lossy())
            } else {
                name
            };
            out.push((label, p.clone(), md.len(), ext_category(&p).to_string(), "real"));
        }
    }
    for d in dirs {
        scan_dir(&d, out, depth + 1, min, cap_files);
    }
}

/// C's own `-b` line: "... 8388608 -> 2851344 (2.942), 345.9 MB/s, 1648.8 MB/s".
fn c_arm(path: &str, lvl: i32) -> Option<(f64, f64, usize)> {
    let out = Command::new(ZSTD)
        .args(["--ultra", &format!("-b{lvl}"), "-i1", "-T1", path])
        .output()
        .ok()?;
    let raw = String::from_utf8_lossy(&out.stderr).into_owned()
        + &String::from_utf8_lossy(&out.stdout);
    let line = raw
        .split(|c: char| c.is_control())
        .filter(|l| l.matches("MB/s").count() >= 2 && l.contains("->"))
        .next_back()?
        .to_string();
    let csize: usize = line.split("->").nth(1)?.split_whitespace().next()?.parse().ok()?;
    let mut sp = Vec::new();
    for seg in line.split("MB/s") {
        if let Some(t) = seg.split_whitespace().next_back() {
            if let Ok(v) = t.trim_end_matches(',').parse::<f64>() {
                sp.push(v);
            }
        }
    }
    if sp.len() < 2 {
        return None;
    }
    Some((sp[0], sp[1], csize))
}

fn measure(path: &std::path::Path, lvl: i32, cap: usize, n: usize, want_c: bool) -> Result<String, String> {
    let f = std::fs::read(path).map_err(|e| e.to_string())?;
    let s = &f[..f.len().min(cap)];
    if s.is_empty() {
        return Err("empty".into());
    }
    let p = rusty_zstd::compression_params(lvl, Some(s.len() as u64)).map_err(|e| format!("{e:?}"))?;
    let z = rusty_zstd::compress_with_params(s, p, false).map_err(|e| format!("{e:?}"))?;
    let mb = s.len() as f64 / 1_048_576.0;

    // Two independent best-of-N encode arms: the second is the null arm.
    let mut enc = [f64::MAX; 2];
    for arm in &mut enc {
        let _ = rusty_zstd::compress_with_params(s, p, false); // warmup, discarded
        for _ in 0..n {
            let t = Instant::now();
            let q = rusty_zstd::compress_with_params(s, p, false).map_err(|e| format!("{e:?}"))?;
            let e = t.elapsed().as_secs_f64();
            std::hint::black_box(q.len());
            if e < *arm {
                *arm = e;
            }
        }
    }
    // Decode into a REUSED buffer, as C's -b does.
    let mut buf = Vec::with_capacity(s.len());
    let mut dec = f64::MAX;
    rusty_zstd::decompress_into(&mut buf, &z).map_err(|e| format!("{e:?}"))?;
    for _ in 0..n {
        buf.clear();
        let t = Instant::now();
        rusty_zstd::decompress_into(&mut buf, &z).map_err(|e| format!("{e:?}"))?;
        let e = t.elapsed().as_secs_f64();
        if e < dec {
            dec = e;
        }
    }
    if buf != s {
        return Err("round-trip mismatch".into());
    }

    let spread = (enc[0].max(enc[1]) / enc[0].min(enc[1]) - 1.0) * 100.0;
    let (mut ce, mut cd, mut cs) = (0.0, 0.0, 0usize);
    if want_c {
        let tmp = std::env::temp_dir().join("rzstd_sim.bin");
        if std::fs::write(&tmp, s).is_ok() {
            if let Some(r) = c_arm(&tmp.to_string_lossy(), lvl) {
                ce = r.0;
                cd = r.1;
                cs = r.2;
            }
        }
    }
    Ok(format!(
        concat!(
            "{{\"ok\":true,\"level\":{},\"bytes\":{},\"csize\":{},\"ratio\":{:.4},",
            "\"enc_mbps\":{:.3},\"dec_mbps\":{:.3},\"spread_pct\":{:.3},",
            "\"c_enc_mbps\":{:.3},\"c_dec_mbps\":{:.3},\"c_csize\":{}}}"
        ),
        lvl,
        s.len(),
        z.len(),
        s.len() as f64 / z.len() as f64,
        mb / enc[0],
        mb / dec,
        spread,
        ce,
        cd,
        cs
    ))
}

fn query(path: &str, key: &str) -> Option<String> {
    let q = path.split_once('?')?.1;
    for kv in q.split('&') {
        if let Some((k, v)) = kv.split_once('=') {
            if k == key {
                return Some(pct_decode(v));
            }
        }
    }
    None
}

fn pct_decode(s: &str) -> String {
    let b = s.as_bytes();
    let mut out = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'%' && i + 2 < b.len() {
            if let Ok(v) = u8::from_str_radix(&s[i + 1..i + 3], 16) {
                out.push(v);
                i += 3;
                continue;
            }
        }
        out.push(if b[i] == b'+' { b' ' } else { b[i] });
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn respond(st: &mut TcpStream, status: &str, ctype: &str, body: &[u8]) {
    let h = format!(
        "HTTP/1.1 {status}\r\nContent-Type: {ctype}\r\nContent-Length: {}\r\n\
         Cache-Control: no-store\r\nConnection: close\r\n\r\n",
        body.len()
    );
    let _ = st.write_all(h.as_bytes());
    let _ = st.write_all(body);
    let _ = st.flush();
}

fn json_escape(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\\' => "\\\\".chars().collect(),
            c if (c as u32) < 0x20 => ' '.to_string().chars().collect(),
            c => vec![c],
        })
        .collect()
}

fn handle(mut st: TcpStream) {
    let mut line = String::new();
    {
        let mut r = BufReader::new(match st.try_clone() {
            Ok(c) => c,
            Err(_) => return,
        });
        if r.read_line(&mut line).is_err() {
            return;
        }
    }
    let path = match line.split_whitespace().nth(1) {
        Some(p) => p.to_string(),
        None => return,
    };

    if path == "/" || path.starts_with("/?") {
        respond(&mut st, "200 OK", "text/html; charset=utf-8", PAGE.as_bytes());
        return;
    }
    if path.starts_with("/api/corpora") {
        // `dir=` rescans real files off disk and REPLACES the registry;
        // no argument restores the built-in corpora.
        let mut note = String::new();
        if let Some(d) = query(&path, "dir") {
            let d = d.trim().to_string();
            if !d.is_empty() {
                let root = PathBuf::from(&d);
                if !root.is_dir() {
                    let body = format!(
                        "{{\"error\":\"not a directory: {}\"}}",
                        json_escape(&d)
                    );
                    respond(&mut st, "200 OK", "application/json", body.as_bytes());
                    return;
                }
                let min: u64 = query(&path, "min").and_then(|v| v.parse().ok()).unwrap_or(65536);
                let mut v = Vec::new();
                scan_dir(&root, &mut v, 0, min, 400);
                v.sort_by(|a, b| b.2.cmp(&a.2)); // biggest first: they time best
                note = format!("scanned {} -> {} files", root.display(), v.len());
                *REGISTRY.lock().unwrap() = v;
            }
        } else if REGISTRY.lock().unwrap().is_empty() {
            *REGISTRY.lock().unwrap() = builtin();
        }
        if query(&path, "reset").as_deref() == Some("1") {
            *REGISTRY.lock().unwrap() = builtin();
            note = "restored built-in corpora".into();
        }
        let reg = REGISTRY.lock().unwrap();
        let items: Vec<String> = reg
            .iter()
            .map(|(name, p, len, cat, prov)| {
                format!(
                    "{{\"name\":\"{}\",\"bytes\":{},\"category\":\"{}\",\"provenance\":\"{}\",\"path\":\"{}\"}}",
                    json_escape(name),
                    len,
                    json_escape(cat),
                    prov,
                    json_escape(&p.display().to_string())
                )
            })
            .collect();
        if !note.is_empty() {
            println!("  {note}");
        }
        let body = format!("[{}]", items.join(","));
        respond(&mut st, "200 OK", "application/json", body.as_bytes());
        return;
    }
    if path.starts_with("/api/run") {
        let file = query(&path, "file").unwrap_or_default();
        let lvl: i32 = query(&path, "level").and_then(|v| v.parse().ok()).unwrap_or(1);
        let cap: usize = query(&path, "cap").and_then(|v| v.parse().ok()).unwrap_or(8 << 20);
        let n: usize = query(&path, "n").and_then(|v| v.parse().ok()).unwrap_or(10).clamp(1, 200);
        let want_c = query(&path, "c").as_deref() == Some("1");
        let target = REGISTRY
            .lock()
            .unwrap()
            .iter()
            .find(|(nm, _, _, _, _)| *nm == file)
            .map(|(_, p, _, _, _)| p.clone());
        let body = match target {
            None => "{\"ok\":false,\"error\":\"no such file\"}".to_string(),
            Some(p) => match measure(&p, lvl, cap, n, want_c) {
                Ok(j) => j,
                Err(e) => format!("{{\"ok\":false,\"error\":\"{}\"}}", json_escape(&e)),
            },
        };
        respond(&mut st, "200 OK", "application/json", body.as_bytes());
        return;
    }
    respond(&mut st, "404 Not Found", "text/plain", b"not found");
}

fn main() {
    let port: u16 = std::env::args().nth(1).and_then(|s| s.parse().ok()).unwrap_or(7878);
    let files = builtin();
    let (real, synth): (Vec<_>, Vec<_>) = files.iter().partition(|e| e.4 == "real");
    *REGISTRY.lock().unwrap() = files.clone();

    let listener = match TcpListener::bind(("127.0.0.1", port)) {
        Ok(l) => l,
        Err(e) => {
            eprintln!("bind 127.0.0.1:{port} failed: {e}");
            return;
        }
    };
    println!("rusty_zstd live transfer-rate simulator");
    if files.is_empty() {
        println!("  no built-in corpora found -- point the tool at a directory instead");
    } else {
        println!(
            "  built-in: {} files -- {} REAL (Silesia), {} SYNTHETIC (generated by recipe)",
            files.len(),
            real.len(),
            synth.len()
        );
    }
    println!("  scan any folder of real files from the page's 'Scan folder' box");
    println!(
        "  C arm: {}",
        if Path::new(ZSTD).exists() { ZSTD } else { "NOT FOUND (C columns stay blank)" }
    );
    println!("\n  ->  http://127.0.0.1:{port}\n");
    println!("Serving one request at a time so the arms never contend. Ctrl-C to stop.");
    for st in listener.incoming().flatten() {
        handle(st);
    }
}
